sonar.projectKey=minattinho_fakestore-api-tests
sonar.organization=minattinho
sonar.projectName=Platzi Fake Store API Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8

# As asserções são feitas com os expect* do PactumJS, que o Sonar não reconhece
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*.spec.ts
